# Generated by Django 4.0 on 2021-12-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticateUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disk_space',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
