# Generated by Django 4.0 on 2021-12-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticateUser', '0002_user_disk_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disk_space',
            field=models.IntegerField(default=50),
        ),
    ]
