# Generated by Django 4.0 on 2021-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticateUser', '0003_alter_user_disk_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maximum_capacity',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='disk_space',
            field=models.IntegerField(),
        ),
    ]
