# Generated by Django 4.0 on 2021-12-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticateUser', '0005_userpaymentaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disk_space',
            field=models.IntegerField(default=0),
        ),
    ]
