# Generated by Django 4.0 on 2021-12-12 18:19

from django.db import migrations, models
import file_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(upload_to=file_management.models.get_upload_path),
        ),
    ]
