# Generated by Django 4.0 on 2021-12-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_alter_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.SlugField(default='ffffffffffffffffffff', max_length=100),
            preserve_default=False,
        ),
    ]
