# Generated by Django 4.0 on 2021-12-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0005_file_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='price',
            field=models.FloatField(default=1.23),
            preserve_default=False,
        ),
    ]
