# Generated by Django 4.0 on 2021-12-21 14:46

from django.db import migrations, models
import file_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0007_file_expire_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='other_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=file_management.models.get_upload_path),
        ),
    ]
